language: node_js
node_js:
  - 9.2.0
  - 9.0.0
deploy:
  provider: npm
  email: dev@knowre.com
  api_key:
    secure: >-
      vcdzCBCk/9X0CxtM4rYkPbhV9QibzsGGMJyDf4MaDP2gZy6uo62dAIoE81AbkDkiiAEAn+GFtqCL/GbERQvAVTtX46L8H4O7aAE84JSMaWdjMuLLhftvgnzaSUHZNFWZ7tI0Oq/mmEKCPK9H+EU0q6UJsTirP9YcKxrSoULutB0nc/JcjnLBqSELujXFmPgDkNmeU6Pq4Ztm/YR6VRZEleL88v00aNr884vNc/whNzjt05+g+lMrHhi68BF12aYUGDgsuQIbBwevCNW6eHcQECdKSBHxL3yIL6Sq86H6c3U2DlUMigauqk9OULCfC4YSx4iCqqGP/+Nu2AbKC19DAwUMHmQkF9UqiqiacYCb+E7Dig6sJ1iJE1ANb5l/i3DHsqJaIuSYzTR+3nXcV559+nvSnN/P9LQBQ+yRKytel4MCTOS/uf5UkedrTerW1L3f/hxaRgYXBmSdFfs6SFh+dwkunEoJrUBkpwbjTeTaC+lacjFRhTgFDUSWuMCsfvocCuo+MjIjbH5LVKaE/rDkDiZjGqPYb47IPg3pN248cFyICpjvpXqvidYEjrnjKKsy5hgNqpIDsR0OjgP8hzaezgKXXbrm5uWbmA9Yj9Qd4SK0G5MpaCWSfrZJJZQkEcbcJSWJOzVe4X0RsuPCF+fJ4KI//fwgDxXupTZpqQzsL2k=
  on:
    branch: stable
    node_js: 9.2.0
notifications:
  slack:
    secure: >-
      Yuhbxm0O53j13P2MvZ3QeUrbWmEzOyxLsFeNMLPJubSkGsM1XXo2BUd0yGDjWoX/aQwModZv/emR5K31PwXtKNbFf11cRC1Ukkxz6DoDTEmQSTjEk+1SljP2FRJB6qot8zQI6KDqfplvwLgvv6llxqBfCm83Gv3HaegKKzdaHOC70jAiGJkeIwGcsV8sBtbax04EYgSkikc2SwAQSTbXfJmuuoTL88iQw7PkJeuD5Ua2BlZGG5n9iJUuxl4LkeJXJRyM6hhxWS1yl7Ch0ljOEvce39rEHjrF4H8htfVdyTUkCscJIcDWURStNIxiEjaFq0CeHno532H4FCYKiL0EQznTOXjxyLdtHAORz44UDZ3PsFtGuzRVYtuTjj4rQVp3rjM5UMC9amhJzUKOJkIyk8+9FTVX0Fk9xtuNQOmhx+obk2Lc4Bnt9CjJlF4cPKo4/QB6drhPlcSa6VsvfzqzvAsjl7/JFP/rUnCHjYLTfRx5jNFYGkccEx4y792FDzzpbRDq48Gm7eUdf1NqjxwJplibLWmPiZBqIIZxSHlaXyntBUKOHSZm0sWWzK7rfeqWAwgYhCkJq6S8c/+8QNjbn0HvDqArxqdUO6wIGF80G7eNe1XHcCXKEf4Zv8fdLcO7ednfIBpvVV7eUEQf+mB0YbEDh0cBBwK2WlNiYM1Wtbs=
