language: node_js
node_js:
- 10.15.2
- 10.0.0
deploy:
  provider: npm
  email: dev@knowre.com
  api_key:
    secure: rPf3hwbJiUiZanwaw7BTF4tXYzYyzo41ov3LF6HDQqtfmbRPraM9v3LCA3bO4EkPykCIMYPlUDFqR85iXccZdWiBZlHw0arDfgh7GtOlFeyg3hHo0/Eu1SGmNmzREfVQlwSO7SuIz4u9ZlyGY82ahcJm1WJoAzxPLmGo+Nd4im8f9OSDG2IwOKT3r+3V4Lh7eKepO1j/Wk8klSX7VgiM30lvCq+mZwB/BYSkgl0BITd4yu+mNSk/5Ff1eyETWd8LYpyyXErUlg517mBZ5kyptWM3Q9isoMYhM11p/v7IPXgzxAFU79ha5kSy3bwrFeOLznmmvl5XLded+HUtMrLxGrWpApHqDyo1ZxMRVNdDJhyBt/1GDRefaJMxbQ6mP3bsbnZok9zB7wchjK9zbUpTmTY4u6zQWHsjf5Lg2HZLhRiRYBsc19H6FGpYWLpVFIvnrrKe6ZdLyUtdyktQjkcgD42KRYfJEprHfQm2/VE4qOPXon074+nEc8IHOBvlVmUB33w+6sFbbYLc86tFXP+A9y4/mb+e4rYZ7T47ffBVmmBvi+0v+pLgf3zVEgVVZnUGIOnjHejm+VFvLBgogN+STv/KxJk5rEWIulNOaJbmC2t9HM3tCJo+/s4uKrDcK537Mg6j5ZbQFAQc1YCVy29YX6z1bkanYoL+f1G4djfHXPQ=
  on:
    branch: stable
    node_js: 10.15.2
notifications:
  slack:
    secure: Yuhbxm0O53j13P2MvZ3QeUrbWmEzOyxLsFeNMLPJubSkGsM1XXo2BUd0yGDjWoX/aQwModZv/emR5K31PwXtKNbFf11cRC1Ukkxz6DoDTEmQSTjEk+1SljP2FRJB6qot8zQI6KDqfplvwLgvv6llxqBfCm83Gv3HaegKKzdaHOC70jAiGJkeIwGcsV8sBtbax04EYgSkikc2SwAQSTbXfJmuuoTL88iQw7PkJeuD5Ua2BlZGG5n9iJUuxl4LkeJXJRyM6hhxWS1yl7Ch0ljOEvce39rEHjrF4H8htfVdyTUkCscJIcDWURStNIxiEjaFq0CeHno532H4FCYKiL0EQznTOXjxyLdtHAORz44UDZ3PsFtGuzRVYtuTjj4rQVp3rjM5UMC9amhJzUKOJkIyk8+9FTVX0Fk9xtuNQOmhx+obk2Lc4Bnt9CjJlF4cPKo4/QB6drhPlcSa6VsvfzqzvAsjl7/JFP/rUnCHjYLTfRx5jNFYGkccEx4y792FDzzpbRDq48Gm7eUdf1NqjxwJplibLWmPiZBqIIZxSHlaXyntBUKOHSZm0sWWzK7rfeqWAwgYhCkJq6S8c/+8QNjbn0HvDqArxqdUO6wIGF80G7eNe1XHcCXKEf4Zv8fdLcO7ednfIBpvVV7eUEQf+mB0YbEDh0cBBwK2WlNiYM1Wtbs=